// alarm metrics

export const alarmsMetrics = [
  {
    title: 'Patient Rate',
    value: 60,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 51,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 70,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 40,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
  {
    title: 'Patient Rate',
    value: 80,
    unit: 'BPM',
    lowerLimit: 30,
    upperLimit: 50,
  },
];
